spring:
  application:
    name: demo

  mvc:
    view:
      prefix: /view/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  file:
    upload-dir: C:/VBeat/uploads

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Vbeat
<<<<<<< HEAD
    username: root 
=======
    username: root
>>>>>>> d97afe1cd422394f5e686799cf3f9174862578f5
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: gPfuf0715@gmail.com
    password: iynvmwsrahjavfah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m

kakao:
  client-id: a61e525034de3c19b48fd2f26eb1316d
  client-secret: E6JjFumIiEDQs7OUJW496mImFzibO1cR
  redirect-uri: http://localhost:8080/oauth/kakao/callback

github:
  client-id: Iv23liV6kMdOeCSDEsZB
  client-secret: 497da41cde1cd7de73401c6100a12e8d1345f373
  redirect-uri: http://localhost:8080/oauth/github/callback

google:
  client-id: 136270481858-1lt34e28j8hp9sf09qhb515qrntcvlhl.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8080/oauth/google/callback
