spring:
  application:
    name: demo

  mvc:
    view:
      prefix: /view/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  file:
    upload-dir: C:/VBeat/uploads

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vbeat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: MySecret1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: gPfuf0715@gmail.com
    password: iynvmwsrahjavfah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m

kakao:
  client-id: a61e525034de3c19b48fd2f26eb1316d
  client-secret: E6JjFumIiEDQs7OUJW496mImFzibO1cR
  redirect-uri: http://localhost:8080/oauth/kakao/callback

google:
  client-id: 136270481858-1lt34e28j8hp9sf09qhb515qrntcvlhl.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8080/oauth/google/callback

matgim:
  base-url: "https://api.matgim.ai/54edkvw2hn"
  api-key: ${MATGIM_API_KEY}
  path: "/api-keyword-slang"

  timeout-ms: 800
  doc-max: 1000
  log-cooldown-ms: 10000
  fail-threshold: 3
  disable-ms: 30000
  cache-ttl-ms: 3000
  cache-max-size: 5000
  cache-cleanup-interval-ms: 10000
